services:
  api:
    volumes: [] # Remove bind mount in production
    environment:
      - DEBUG=False

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes: [] # Remove bind mounts in production
    environment:
      - VITE_API_TARGET=http://api:8000
